# Generated by Django 6.1 on 2026-08-25 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Practical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practical_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('aim', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('theory', models.TextField(blank=True)),
                ('procedure', models.TextField(blank=True)),
                ('code', models.TextField(blank=True)),
                ('output_image', models.ImageField(blank=True, null=True, upload_to='practical_outputs/')),
                ('viva_questions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicals', to='practicals.subject')),
            ],
            options={
                'ordering': ['practical_number'],
                'unique_together': {('subject', 'practical_number')},
            },
        ),
    ]
